try:
    print(c)
except Exception as ex:
    print(ex)
